include macchiato.conf

font_family	JetBrainsMono Nerd Font Mono
font_size	16

disable_ligatures no
enable_audio_bell no

shell fish
shell_integration disabled

cursor_shape block

url_style curly

remember_window_size 	no
initial_window_width	78c
initial_window_height	23c
window_padding_width	30
curso_blink_interval	0

background_opacity	0.8
scrollbar_handle_opacity 0
scrollbar_track_opacity 0
scrollbar_track_hover_opacity 0
confirm_os_window_close 0

sync_to_monitor no

repaint_delay 8
input_delay 3

cursor_trail 3


# základ
foreground #ffffff
background #1a1e2a

# normal colors
color0  #1a1e2a   # black (bg1)
color1  #fa5ead   # red (pink)
color2  #00fbad   # green
color3  #ffdf5f   # yellow (ponechal som pôvodný)
color4  #5eadfc   # blue
color5  #fa5ead   # magenta (pink)
color6  #242D42   # cyan (bg2)
color7  #ffffff   # white

# bright colors
color8  #1a1e2a
color9  #fa5ead
color10 #00fbad
color11 #ffdf5f
color12 #5eadfc
color13 #fa5ead
color14 #6a6f87   # grey
color15 #eff1f5

selection_background #242D42
selection_foreground #ffffff
cursor #5eadfc
